[package]
name = "nes_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = {version = "0.10.0", default_features = false}
log = "0.4.17"
modular-bitfield = "0.11.2"
strum_macros = "0.24.3"

[profile.release]
lto = true
codegen-units=1

[profile.dev]
split-debuginfo = "unpacked"
