[package]
name = "nes_web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
log = "0.4.17"
nes_core = { path = "../nes_core" }
wasm-bindgen = "0.2.83"
web-sys = "0.3.60"
wee_alloc = "0.4.5"

