[package]
name = "nes_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
log = {version="0.4.17", features=["release_max_level_off"]}
modular-bitfield = "0.11.2"
nom = "7.1.3"
strum_macros = "0.24.3"
thiserror = "1.0.38"
image = { version = "0.24.5", default_features = false}

[dev-dependencies]
env_logger = "0.10.0"
test-log = "0.2.11"

