[package]
name = "nescli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.1", features = ["derive"] }
image = { version = "0.24.5", default_features = false, features = ["png"] }
nes_core = { path = "../nes_core" }
