use crate::ines::INesFile;
use crate::mcu::Mcu;
use crate::nes::apu::{Apu, AudioDriver};
use crate::nes::controller::{Button, Controller};
use crate::nes::lower_ram::LowerRam;
use crate::nes::mapper::Cartridge;
use crate::nes::ppu::Ppu;
use crate::render::Render;
use log::trace;

pub mod apu;
pub mod controller;
mod lower_ram;
mod mapper;
pub mod ppu;

pub struct NesMcu<R: Render, D: AudioDriver> {
    lower_ram: LowerRam,
    ppu: Ppu<R>,
    controller: Controller,
    cartridge: Cartridge,
    apu: Apu<D>,
    oam_dma_pending: bool,
    /// Pending DMC DMA: (address, is_reload).
    dmc_dma_pending: Option<(u16, bool)>,
    /// CPU data bus open bus value: the last value read by the CPU.
    /// Reading write-only or unmapped addresses returns this value.
    open_bus: u8,
}

impl<R: Render, D: AudioDriver> NesMcu<R, D> {
    pub fn new(file: &INesFile, renderer: R, audio_driver: D) -> Self {
        let cartridge = mapper::create_cartridge(file);
        let ppu = Ppu::new(renderer);

        Self {
            lower_ram: LowerRam::new(),
            ppu,
            controller: Controller::new(),
            cartridge,
            apu: Apu::new(audio_driver),
            oam_dma_pending: false,
            dmc_dma_pending: None,
            open_bus: 0,
        }
    }

    pub fn reset(&mut self) {
        self.ppu.reset();
        self.apu.reset();
    }

    fn ppu_dma(&mut self, address: u8) {
        trace!("ppu dma");
        let addr = (address as u16) << 8;
        let mut buf = [0x00u8; 0x100];
        for (i, item) in buf.iter_mut().enumerate() {
            *item = self.read(addr + i as u16);
        }
        self.ppu.oam_dma(&buf);
        self.cartridge.on_oam_dma();
        self.oam_dma_pending = true;
    }

    /// Tick PPU by one dot.
    /// Pattern data is passed through from the cartridge for rendering.
    pub fn tick_ppu(&mut self) {
        let (scanline, dot) = self.ppu.timing();
        let rendering_enabled = self.ppu.rendering_enabled();
        self.ppu.tick(&self.cartridge);
        self.cartridge.on_ppu_tick(scanline, dot, rendering_enabled);
    }

    /// Tick APU frame counter. Returns true if frame IRQ should be triggered.
    pub fn tick_apu(&mut self) -> bool {
        self.apu.tick()
    }

    pub fn irq_pending(&self) -> bool {
        self.apu.request_irq() || self.cartridge.irq_pending()
    }

    pub fn flush_audio(&mut self) {
        self.apu.flush();
    }

    pub fn take_oam_dma_pending(&mut self) -> bool {
        std::mem::take(&mut self.oam_dma_pending)
    }

    /// Re-check if DMC DMA is needed after a CPU write to $4015.
    pub fn recheck_dmc_dma(&mut self) {
        self.apu.recheck_dmc_dma();
    }

    /// Queue a DMC DMA request generated by the APU. The actual bus read is
    /// performed later by the CPU-side DMA scheduler so side-effecting reads
    /// (e.g. $4016, $2007) can be modeled correctly.
    /// Returns (took_pending, is_reload) if a DMA was queued.
    pub fn take_dmc_dma_pending(&mut self) -> Option<bool> {
        if let Some((addr, is_reload)) = self.apu.take_dmc_dma_request() {
            self.dmc_dma_pending = Some((addr, is_reload));
            Some(is_reload)
        } else {
            None
        }
    }

    pub fn take_dmc_dma_address(&mut self) -> Option<u16> {
        self.dmc_dma_pending.take().map(|(addr, _)| addr)
    }

    pub fn supply_dmc_dma_byte(&mut self, byte: u8) {
        self.apu.supply_dmc_byte(byte);
    }

    /// Perform the DMC DMA bus read while the CPU is reading `cpu_read_addr`.
    /// This models the read4 test behavior where the overlap can trigger an
    /// extra side-effecting CPU register read before the actual sample fetch.
    pub fn perform_dmc_dma_read(&mut self, sample_addr: u16, cpu_read_addr: u16) -> u8 {
        match cpu_read_addr {
            0x4016 | 0x4017 => {
                // DMC DMA during controller read causes an extra controller read.
                let _ = self.read(cpu_read_addr);
            }
            0x2007 => {
                // DMC DMA during PPUDATA read causes extra PPUDATA reads.
                // The read4 tests accept 2-3 extra reads depending on power-on
                // CPU/PPU phase; use the stable 2-read variant here.
                let _ = self.read(0x2007);
                let _ = self.read(0x2007);
            }
            _ => {}
        }

        self.read(sample_addr)
    }

    pub fn press_button(&mut self, button: Button) {
        self.controller.a.press(button);
    }

    pub fn release_button(&mut self, button: Button) {
        self.controller.a.release(button);
    }

    pub fn ppu_timing(&self) -> (u16, u16) {
        self.ppu.timing()
    }

    pub fn ppu(&self) -> &Ppu<R> {
        &self.ppu
    }

    pub fn read_nametable(&self, address: u16) -> u8 {
        self.cartridge.read_nametable(address)
    }

    pub fn dump_ppu_state(&self) -> String {
        self.ppu.dump_state(&self.cartridge)
    }
}

impl<R: Render, D: AudioDriver> Mcu for NesMcu<R, D> {
    fn read(&mut self, address: u16) -> u8 {
        let value = match address {
            0x0000..=0x1fff => self.lower_ram.read(address),
            0x2000..=0x3fff => self.ppu.read(address, &mut self.cartridge),
            0x4015 => self.apu.read(address),
            0x4016 | 0x4017 => self.controller.read(address),
            // Write-only APU/IO registers and unused test registers: open bus
            0x4000..=0x401f => self.open_bus,
            // Unallocated I/O space: open bus
            0x4020..=0x40ff => self.open_bus,
            0x4100..=0xffff => self.cartridge.read(address),
        };
        self.open_bus = value;
        value
    }

    fn peek(&self, address: u16) -> u8 {
        match address {
            0x0000..=0x1fff => self.lower_ram.peek(address),
            0x2000..=0x3fff => self.ppu.peek(address, &self.cartridge),
            0x4015 => self.apu.peek(address),
            0x4016 | 0x4017 => self.controller.peek(address),
            0x4000..=0x401f => self.open_bus,
            0x4020..=0x40ff => self.open_bus,
            0x4100..=0xffff => self.cartridge.peek(address),
        }
    }

    fn write(&mut self, address: u16, value: u8) {
        self.open_bus = value;
        match address {
            0x0000..=0x1fff => self.lower_ram.write(address, value),
            0x2000..=0x3fff => self.ppu.write(address, value, &mut self.cartridge),
            0x4000..=0x401f => match address {
                0x4014 => self.ppu_dma(value),
                0x4016 => self.controller.write(address, value),
                _ => self.apu.write(address, value),
            },
            // Unallocated I/O space: writes are ignored
            0x4020..=0x40ff => {}
            0x4100..=0xffff => self.cartridge.write(address, value),
        }
    }

    fn take_dmc_dma_address(&mut self) -> Option<u16> {
        self.take_dmc_dma_address()
    }

    fn perform_dmc_dma_read(&mut self, sample_addr: u16, cpu_read_addr: u16) -> u8 {
        self.perform_dmc_dma_read(sample_addr, cpu_read_addr)
    }

    fn supply_dmc_dma_byte(&mut self, byte: u8) {
        self.supply_dmc_dma_byte(byte);
    }
}

#[cfg(test)]
mod tests;
