[
    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),

    // 16 elements
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
    ArrayVec::from_array_empty([Microcode::Kill; 7]),
]
