use std::fmt::{Display, Formatter};

#[derive(Debug, Clone, Copy)]
enum Addressing {
    None,
    Immediate,
    Absolute,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndexedIndirect,
    IndirectIndexed,
}

impl Addressing {
    fn format(self, f: &mut Formatter<'_>, low: u8, high: u8) -> Result<(), std::fmt::Error> {
        match self {
            Addressing::None => Ok(()),
            Addressing::Immediate => write!(f, "#${:02X}", low),
            Addressing::Absolute => write!(f, "${:02X}{:02X}", high, low),
            Addressing::ZeroPage => write!(f, "${:02X}", low),
            Addressing::ZeroPageX => write!(f, "${:02X},X", low),
            Addressing::ZeroPageY => write!(f, "${:02X},Y", low),
            Addressing::AbsoluteX => write!(f, "${:02X}{:02X},X", high, low),
            Addressing::AbsoluteY => write!(f, "${:02X}{:02X},Y", high, low),
            Addressing::Indirect => write!(f, "(${:02X}{:02X})", high, low),
            Addressing::IndexedIndirect => write!(f, "(${:02X},X)", low),
            Addressing::IndirectIndexed => write!(f, "(${:02X}),Y", low),
        }
    }

    fn operand_len(self) -> usize {
        match self {
            Addressing::None => 0,
            Addressing::Immediate => 1,
            Addressing::Absolute => 2,
            Addressing::ZeroPage => 1,
            Addressing::ZeroPageX => 1,
            Addressing::ZeroPageY => 1,
            Addressing::AbsoluteX => 2,
            Addressing::AbsoluteY => 2,
            Addressing::Indirect => 2,
            Addressing::IndexedIndirect => 1,
            Addressing::IndirectIndexed => 1,
        }
    }
}

#[derive(Debug, Clone, Copy)]
struct Op {
    name: &'static str,
    addressing: Addressing,
}

impl Op {
    const fn new(name: &'static str, addressing: Addressing) -> Self {
        Self { name, addressing }
    }

    fn format(self, f: &mut Formatter<'_>, low: u8, high: u8) -> Result<(), std::fmt::Error> {
        write!(f, "{} ", self.name)?;
        self.addressing.format(f, low, high)
    }
}

pub struct AsAsm(pub u8, pub u8, pub u8);

impl Display for AsAsm {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        let op = OPCODES[self.0 as usize];
        write!(f, "{:02X} ", self.0)?;
        match op.addressing.operand_len() {
            1 => write!(f, "{:02X}     ", self.1)?,
            2 => {
                write!(f, "{:02X} ", self.1)?;
                write!(f, "{:02X}  ", self.2)?;
            }
            _ => write!(f, "       ")?,
        }
        op.format(f, self.1, self.2)
    }
}

static OPCODES: [Op; 256] = [
    /* 0x00 */ Op::new("BRK", Addressing::None),
    /* 0x01 */ Op::new("ORA", Addressing::IndexedIndirect),
    /* 0x02 */ Op::new("KIL", Addressing::None),
    /* 0x03 */ Op::new("SLO", Addressing::IndexedIndirect),
    /* 0x04 */ Op::new("NOP", Addressing::ZeroPage),
    /* 0x05 */ Op::new("ORA", Addressing::ZeroPage),
    /* 0x06 */ Op::new("ASL", Addressing::ZeroPage),
    /* 0x07 */ Op::new("SLO", Addressing::ZeroPage),
    /* 0x08 */ Op::new("PHP", Addressing::None),
    /* 0x09 */ Op::new("ORA", Addressing::Immediate),
    /* 0x0A */ Op::new("ASL", Addressing::None),
    /* 0x0B */ Op::new("ANC", Addressing::Immediate),
    /* 0x0C */ Op::new("NOP", Addressing::Absolute),
    /* 0x0D */ Op::new("ORA", Addressing::Absolute),
    /* 0x0E */ Op::new("ASL", Addressing::Absolute),
    /* 0x0F */ Op::new("SLO", Addressing::Absolute),
    /* 0x10 */ Op::new("BPL", Addressing::None),
    /* 0x11 */ Op::new("ORA", Addressing::IndirectIndexed),
    /* 0x12 */ Op::new("KIL", Addressing::None),
    /* 0x13 */ Op::new("SLO", Addressing::IndirectIndexed),
    /* 0x14 */ Op::new("NOP", Addressing::ZeroPageX),
    /* 0x15 */ Op::new("ORA", Addressing::ZeroPageX),
    /* 0x16 */ Op::new("ASL", Addressing::ZeroPageX),
    /* 0x17 */ Op::new("SLO", Addressing::ZeroPageX),
    /* 0x18 */ Op::new("CLC", Addressing::None),
    /* 0x19 */ Op::new("ORA", Addressing::AbsoluteY),
    /* 0x1A */ Op::new("NOP", Addressing::None),
    /* 0x1B */ Op::new("SLO", Addressing::AbsoluteY),
    /* 0x1C */ Op::new("NOP", Addressing::AbsoluteX),
    /* 0x1D */ Op::new("ORA", Addressing::AbsoluteX),
    /* 0x1E */ Op::new("ASL", Addressing::AbsoluteX),
    /* 0x1F */ Op::new("SLO", Addressing::AbsoluteX),
    /* 0x20 */ Op::new("JSR", Addressing::Absolute),
    /* 0x21 */ Op::new("AND", Addressing::IndexedIndirect),
    /* 0x22 */ Op::new("KIL", Addressing::None),
    /* 0x23 */ Op::new("RLA", Addressing::IndexedIndirect),
    /* 0x24 */ Op::new("BIT", Addressing::ZeroPage),
    /* 0x25 */ Op::new("AND", Addressing::ZeroPage),
    /* 0x26 */ Op::new("ROL", Addressing::ZeroPage),
    /* 0x27 */ Op::new("RLA", Addressing::ZeroPage),
    /* 0x28 */ Op::new("PLP", Addressing::None),
    /* 0x29 */ Op::new("AND", Addressing::Immediate),
    /* 0x2A */ Op::new("ROL", Addressing::None),
    /* 0x2B */ Op::new("ANC", Addressing::Immediate),
    /* 0x2C */ Op::new("BIT", Addressing::Absolute),
    /* 0x2D */ Op::new("AND", Addressing::Absolute),
    /* 0x2E */ Op::new("ROL", Addressing::Absolute),
    /* 0x2F */ Op::new("RLA", Addressing::Absolute),
    /* 0x30 */ Op::new("BMI", Addressing::None),
    /* 0x31 */ Op::new("AND", Addressing::IndirectIndexed),
    /* 0x32 */ Op::new("KIL", Addressing::None),
    /* 0x33 */ Op::new("RLA", Addressing::IndirectIndexed),
    /* 0x34 */ Op::new("NOP", Addressing::ZeroPageX),
    /* 0x35 */ Op::new("AND", Addressing::ZeroPageX),
    /* 0x36 */ Op::new("ROL", Addressing::ZeroPageX),
    /* 0x37 */ Op::new("RLA", Addressing::ZeroPageX),
    /* 0x38 */ Op::new("SEC", Addressing::None),
    /* 0x39 */ Op::new("AND", Addressing::AbsoluteY),
    /* 0x3A */ Op::new("NOP", Addressing::None),
    /* 0x3B */ Op::new("RLA", Addressing::AbsoluteY),
    /* 0x3C */ Op::new("NOP", Addressing::AbsoluteX),
    /* 0x3D */ Op::new("AND", Addressing::AbsoluteX),
    /* 0x3E */ Op::new("ROL", Addressing::AbsoluteX),
    /* 0x3F */ Op::new("RLA", Addressing::AbsoluteX),
    /* 0x40 */ Op::new("RTI", Addressing::None),
    /* 0x41 */ Op::new("EOR", Addressing::IndexedIndirect),
    /* 0x42 */ Op::new("KIL", Addressing::None),
    /* 0x43 */ Op::new("SRE", Addressing::IndexedIndirect),
    /* 0x44 */ Op::new("NOP", Addressing::ZeroPage),
    /* 0x45 */ Op::new("EOR", Addressing::ZeroPage),
    /* 0x46 */ Op::new("LSR", Addressing::ZeroPage),
    /* 0x47 */ Op::new("SRE", Addressing::ZeroPage),
    /* 0x48 */ Op::new("PHA", Addressing::None),
    /* 0x49 */ Op::new("EOR", Addressing::Immediate),
    /* 0x4A */ Op::new("LSR", Addressing::None),
    /* 0x4B */ Op::new("ALR", Addressing::Immediate),
    /* 0x4C */ Op::new("JMP", Addressing::Absolute),
    /* 0x4D */ Op::new("EOR", Addressing::Absolute),
    /* 0x4E */ Op::new("LSR", Addressing::Absolute),
    /* 0x4F */ Op::new("SRE", Addressing::Absolute),
    /* 0x50 */ Op::new("BVC", Addressing::None),
    /* 0x51 */ Op::new("EOR", Addressing::IndirectIndexed),
    /* 0x52 */ Op::new("KIL", Addressing::None),
    /* 0x53 */ Op::new("SRE", Addressing::IndirectIndexed),
    /* 0x54 */ Op::new("NOP", Addressing::ZeroPageX),
    /* 0x55 */ Op::new("EOR", Addressing::ZeroPageX),
    /* 0x56 */ Op::new("LSR", Addressing::ZeroPageX),
    /* 0x57 */ Op::new("SRE", Addressing::ZeroPageX),
    /* 0x58 */ Op::new("CLI", Addressing::None),
    /* 0x59 */ Op::new("EOR", Addressing::AbsoluteY),
    /* 0x5A */ Op::new("NOP", Addressing::None),
    /* 0x5B */ Op::new("SRE", Addressing::AbsoluteY),
    /* 0x5C */ Op::new("NOP", Addressing::AbsoluteX),
    /* 0x5D */ Op::new("EOR", Addressing::AbsoluteX),
    /* 0x5E */ Op::new("LSR", Addressing::AbsoluteX),
    /* 0x5F */ Op::new("SRE", Addressing::AbsoluteX),
    /* 0x60 */ Op::new("RTS", Addressing::None),
    /* 0x61 */ Op::new("ADC", Addressing::IndexedIndirect),
    /* 0x62 */ Op::new("KIL", Addressing::None),
    /* 0x63 */ Op::new("RRA", Addressing::IndexedIndirect),
    /* 0x64 */ Op::new("NOP", Addressing::ZeroPage),
    /* 0x65 */ Op::new("ADC", Addressing::ZeroPage),
    /* 0x66 */ Op::new("ROR", Addressing::ZeroPage),
    /* 0x67 */ Op::new("RRA", Addressing::ZeroPage),
    /* 0x68 */ Op::new("PLA", Addressing::None),
    /* 0x69 */ Op::new("ADC", Addressing::Immediate),
    /* 0x6A */ Op::new("ROR", Addressing::None),
    /* 0x6B */ Op::new("ARR", Addressing::Immediate),
    /* 0x6C */ Op::new("JMP", Addressing::Indirect),
    /* 0x6D */ Op::new("ADC", Addressing::Absolute),
    /* 0x6E */ Op::new("ROR", Addressing::Absolute),
    /* 0x6F */ Op::new("RRA", Addressing::Absolute),
    /* 0x70 */ Op::new("BVS", Addressing::None),
    /* 0x71 */ Op::new("ADC", Addressing::IndirectIndexed),
    /* 0x72 */ Op::new("KIL", Addressing::None),
    /* 0x73 */ Op::new("RRA", Addressing::IndirectIndexed),
    /* 0x74 */ Op::new("NOP", Addressing::ZeroPageX),
    /* 0x75 */ Op::new("ADC", Addressing::ZeroPageX),
    /* 0x76 */ Op::new("ROR", Addressing::ZeroPageX),
    /* 0x77 */ Op::new("RRA", Addressing::ZeroPageX),
    /* 0x78 */ Op::new("SEI", Addressing::None),
    /* 0x79 */ Op::new("ADC", Addressing::AbsoluteY),
    /* 0x7A */ Op::new("NOP", Addressing::None),
    /* 0x7B */ Op::new("RRA", Addressing::AbsoluteY),
    /* 0x7C */ Op::new("NOP", Addressing::AbsoluteX),
    /* 0x7D */ Op::new("ADC", Addressing::AbsoluteX),
    /* 0x7E */ Op::new("ROR", Addressing::AbsoluteX),
    /* 0x7F */ Op::new("RRA", Addressing::AbsoluteX),
    /* 0x80 */ Op::new("NOP", Addressing::Immediate),
    /* 0x81 */ Op::new("STA", Addressing::IndexedIndirect),
    /* 0x82 */ Op::new("NOP", Addressing::Immediate),
    /* 0x83 */ Op::new("SAX", Addressing::IndexedIndirect),
    /* 0x84 */ Op::new("STY", Addressing::ZeroPage),
    /* 0x85 */ Op::new("STA", Addressing::ZeroPage),
    /* 0x86 */ Op::new("STX", Addressing::ZeroPage),
    /* 0x87 */ Op::new("SAX", Addressing::ZeroPage),
    /* 0x88 */ Op::new("DEY", Addressing::None),
    /* 0x89 */ Op::new("NOP", Addressing::Immediate),
    /* 0x8A */ Op::new("TXA", Addressing::None),
    /* 0x8B */ Op::new("XAA", Addressing::Immediate),
    /* 0x8C */ Op::new("STY", Addressing::Absolute),
    /* 0x8D */ Op::new("STA", Addressing::Absolute),
    /* 0x8E */ Op::new("STX", Addressing::Absolute),
    /* 0x8F */ Op::new("SAX", Addressing::Absolute),
    /* 0x90 */ Op::new("BCC", Addressing::None),
    /* 0x91 */ Op::new("STA", Addressing::IndirectIndexed),
    /* 0x92 */ Op::new("KIL", Addressing::None),
    /* 0x93 */ Op::new("AHX", Addressing::IndirectIndexed),
    /* 0x94 */ Op::new("STY", Addressing::ZeroPageX),
    /* 0x95 */ Op::new("STA", Addressing::ZeroPageX),
    /* 0x96 */ Op::new("STX", Addressing::ZeroPageY),
    /* 0x97 */ Op::new("SAX", Addressing::ZeroPageY),
    /* 0x98 */ Op::new("TYA", Addressing::None),
    /* 0x99 */ Op::new("STA", Addressing::AbsoluteY),
    /* 0x9A */ Op::new("TXS", Addressing::None),
    /* 0x9B */ Op::new("TAS", Addressing::AbsoluteY),
    /* 0x9C */ Op::new("SHY", Addressing::AbsoluteX),
    /* 0x9D */ Op::new("STA", Addressing::AbsoluteX),
    /* 0x9E */ Op::new("SHX", Addressing::AbsoluteY),
    /* 0x9F */ Op::new("AHX", Addressing::AbsoluteY),
    /* 0xA0 */ Op::new("LDY", Addressing::Immediate),
    /* 0xA1 */ Op::new("LDA", Addressing::IndexedIndirect),
    /* 0xA2 */ Op::new("LDX", Addressing::Immediate),
    /* 0xA3 */ Op::new("LAX", Addressing::IndexedIndirect),
    /* 0xA4 */ Op::new("LDY", Addressing::ZeroPage),
    /* 0xA5 */ Op::new("LDA", Addressing::ZeroPage),
    /* 0xA6 */ Op::new("LDX", Addressing::ZeroPage),
    /* 0xA7 */ Op::new("LAX", Addressing::ZeroPage),
    /* 0xA8 */ Op::new("TAY", Addressing::None),
    /* 0xA9 */ Op::new("LDA", Addressing::Immediate),
    /* 0xAA */ Op::new("TAX", Addressing::None),
    /* 0xAB */ Op::new("LAX", Addressing::Immediate),
    /* 0xAC */ Op::new("LDY", Addressing::Absolute),
    /* 0xAD */ Op::new("LDA", Addressing::Absolute),
    /* 0xAE */ Op::new("LDX", Addressing::Absolute),
    /* 0xAF */ Op::new("LAX", Addressing::Absolute),
    /* 0xB0 */ Op::new("BCS", Addressing::None),
    /* 0xB1 */ Op::new("LDA", Addressing::IndirectIndexed),
    /* 0xB2 */ Op::new("KIL", Addressing::None),
    /* 0xB3 */ Op::new("LAX", Addressing::IndirectIndexed),
    /* 0xB4 */ Op::new("LDY", Addressing::ZeroPageX),
    /* 0xB5 */ Op::new("LDA", Addressing::ZeroPageX),
    /* 0xB6 */ Op::new("LDX", Addressing::ZeroPageY),
    /* 0xB7 */ Op::new("LAX", Addressing::ZeroPageY),
    /* 0xB8 */ Op::new("CLV", Addressing::None),
    /* 0xB9 */ Op::new("LDA", Addressing::AbsoluteY),
    /* 0xBA */ Op::new("TSX", Addressing::None),
    /* 0xBB */ Op::new("LAS", Addressing::AbsoluteY),
    /* 0xBC */ Op::new("LDY", Addressing::AbsoluteX),
    /* 0xBD */ Op::new("LDA", Addressing::AbsoluteX),
    /* 0xBE */ Op::new("LDX", Addressing::AbsoluteY),
    /* 0xBF */ Op::new("LAX", Addressing::AbsoluteY),
    /* 0xC0 */ Op::new("CPY", Addressing::Immediate),
    /* 0xC1 */ Op::new("CMP", Addressing::IndexedIndirect),
    /* 0xC2 */ Op::new("NOP", Addressing::Immediate),
    /* 0xC3 */ Op::new("DCP", Addressing::IndexedIndirect),
    /* 0xC4 */ Op::new("CPY", Addressing::ZeroPage),
    /* 0xC5 */ Op::new("CMP", Addressing::ZeroPage),
    /* 0xC6 */ Op::new("DEC", Addressing::ZeroPage),
    /* 0xC7 */ Op::new("DCP", Addressing::ZeroPage),
    /* 0xC8 */ Op::new("INY", Addressing::None),
    /* 0xC9 */ Op::new("CMP", Addressing::Immediate),
    /* 0xCA */ Op::new("DEX", Addressing::None),
    /* 0xCB */ Op::new("AXS", Addressing::Immediate),
    /* 0xCC */ Op::new("CPY", Addressing::Absolute),
    /* 0xCD */ Op::new("CMP", Addressing::Absolute),
    /* 0xCE */ Op::new("DEC", Addressing::Absolute),
    /* 0xCF */ Op::new("DCP", Addressing::Absolute),
    /* 0xD0 */ Op::new("BNE", Addressing::None),
    /* 0xD1 */ Op::new("CMP", Addressing::IndirectIndexed),
    /* 0xD2 */ Op::new("KIL", Addressing::None),
    /* 0xD3 */ Op::new("DCP", Addressing::IndirectIndexed),
    /* 0xD4 */ Op::new("NOP", Addressing::ZeroPageX),
    /* 0xD5 */ Op::new("CMP", Addressing::ZeroPageX),
    /* 0xD6 */ Op::new("DEC", Addressing::ZeroPageX),
    /* 0xD7 */ Op::new("DCP", Addressing::ZeroPageX),
    /* 0xD8 */ Op::new("CLD", Addressing::None),
    /* 0xD9 */ Op::new("CMP", Addressing::AbsoluteY),
    /* 0xDA */ Op::new("NOP", Addressing::None),
    /* 0xDB */ Op::new("DCP", Addressing::AbsoluteY),
    /* 0xDC */ Op::new("NOP", Addressing::AbsoluteX),
    /* 0xDD */ Op::new("CMP", Addressing::AbsoluteX),
    /* 0xDE */ Op::new("DEC", Addressing::AbsoluteX),
    /* 0xDF */ Op::new("DCP", Addressing::AbsoluteX),
    /* 0xE0 */ Op::new("CPX", Addressing::Immediate),
    /* 0xE1 */ Op::new("SBC", Addressing::IndexedIndirect),
    /* 0xE2 */ Op::new("NOP", Addressing::Immediate),
    /* 0xE3 */ Op::new("ISC", Addressing::IndexedIndirect),
    /* 0xE4 */ Op::new("CPX", Addressing::ZeroPage),
    /* 0xE5 */ Op::new("SBC", Addressing::ZeroPage),
    /* 0xE6 */ Op::new("INC", Addressing::ZeroPage),
    /* 0xE7 */ Op::new("ISC", Addressing::ZeroPage),
    /* 0xE8 */ Op::new("INX", Addressing::None),
    /* 0xE9 */ Op::new("SBC", Addressing::Immediate),
    /* 0xEA */ Op::new("NOP", Addressing::None),
    /* 0xEB */ Op::new("USBC", Addressing::Immediate),
    /* 0xEC */ Op::new("CPX", Addressing::Absolute),
    /* 0xED */ Op::new("SBC", Addressing::Absolute),
    /* 0xEE */ Op::new("INC", Addressing::Absolute),
    /* 0xEF */ Op::new("ISC", Addressing::Absolute),
    /* 0xF0 */ Op::new("BEQ", Addressing::None),
    /* 0xF1 */ Op::new("SBC", Addressing::IndirectIndexed),
    /* 0xF2 */ Op::new("KIL", Addressing::None),
    /* 0xF3 */ Op::new("ISC", Addressing::IndirectIndexed),
    /* 0xF4 */ Op::new("NOP", Addressing::ZeroPageX),
    /* 0xF5 */ Op::new("SBC", Addressing::ZeroPageX),
    /* 0xF6 */ Op::new("INC", Addressing::ZeroPageX),
    /* 0xF7 */ Op::new("ISC", Addressing::ZeroPageX),
    /* 0xF8 */ Op::new("SED", Addressing::None),
    /* 0xF9 */ Op::new("SBC", Addressing::AbsoluteY),
    /* 0xFA */ Op::new("NOP", Addressing::None),
    /* 0xFB */ Op::new("ISC", Addressing::AbsoluteY),
    /* 0xFC */ Op::new("NOP", Addressing::AbsoluteX),
    /* 0xFD */ Op::new("SBC", Addressing::AbsoluteX),
    /* 0xFE */ Op::new("INC", Addressing::AbsoluteX),
    /* 0xFF */ Op::new("ISC", Addressing::AbsoluteX),
];
